# Geophysical Inversion
## Homework 6
## Magnús Pálsson

### Problem 1

What is the general solution to the problem $\mathbf{Gm}=\mathbf{d}$, with
$$\begin{bmatrix}
1 & 1 & 0 & 0 \\
0 & 0 & 1 & 1
\end{bmatrix}$$
### Solution

We have 
$$\begin{equation*}
\begin{bmatrix}
1 & 1 & 0 & 0 \\
0 & 0 & 1 & 1
\end{bmatrix}
\begin{bmatrix}
m_1\\
m_2\\
m_3\\
m_4
\end{bmatrix}
=
\begin{bmatrix}
d_1\\
d_2
\end{bmatrix}
\end{equation*}$$

We can see by inspection that both $\mathbf{m}^{par} = [d_1, 0, d_2, 0]^T$ and $\mathbf{m}^{par} = [0, d_1, 0, d_2]^T$ are solutions, let us pick the first one.
Now we need two linearly independant solutions to 

$$\begin{equation*}
\begin{bmatrix}
1 & 1 & 0 & 0 \\
0 & 0 & 1 & 1
\end{bmatrix}
\begin{bmatrix}
m_1\\
m_2\\
m_3\\
m_4
\end{bmatrix}
=
\begin{bmatrix}
0\\
0
\end{bmatrix}
\end{equation*}$$

We can see that $\mathbf{m}^{null(1)} = [1, -1, 0, 0]^T$ and $\mathbf{m}^{null(2)} = [0, 0, 1, -1]^T$ will do the trick
We then have the general solution
$$\begin{equation*}
\mathbf{m}^{gen} =
\begin{bmatrix}
d_1\\
0\\
d_2\\
0
\end{bmatrix}
+ \alpha_1
\begin{bmatrix}
1\\
-1\\
0\\
0
\end{bmatrix}
+ \alpha_2
\begin{bmatrix}
0\\
0\\
1\\
-1
\end{bmatrix}
\end{equation*}$$

### Problem 2

Give some examples of physical problems where the model parameters can be assumed,
with reasonable certainty, to fall between lower and upper bounds (and identify the
bounds).

### Solution

1. Earthquake location. Latitude and longitude are obviously constrained but so is depth, after all, there are no earthquakes in space.
2. Cloud altitude. Clouds are generally not found inside the earth or in space
3. Pressure in an explosive device. A certain amount of pressure is needed to rupture the container which will certainly be larger than 0. Knowledge of the material may improve the lower bound. An upper bound might be found from the amount and type of explosive material, but can also somewhat spuriously be assumed to be lower than the electron-degeneracy pressure required to collapse atoms into neutrons, forming neutronium.

### Problem 3

Use SVD on the data kernel $\mathbf{G} = [1, 1, 1, 1]$ 

The null vectors are different from that given in a previous chapter. Why? Show that the two sets are equivalent

### Solution

In [1]:
import numpy as np

G = np.ones((1,4))

U, S, Vh = np.linalg.svd(G)
print("U")
print(U)
print("-"*20)
print("Eigenvalue")
print(S)
print("-"*20)
print("V")
print(Vh)
print("-"*20)
v1 = Vh[1,:]
v2 = Vh[2,:]
v3 = Vh[3,:]
print("The null vectors are")
print("-"*20)
print(v1)
print(v2)
print(v3)

U
[[-1.]]
--------------------
Eigenvalue
[2.]
--------------------
V
[[-0.5        -0.5        -0.5        -0.5       ]
 [-0.5         0.83333333 -0.16666667 -0.16666667]
 [-0.5        -0.16666667  0.83333333 -0.16666667]
 [-0.5        -0.16666667 -0.16666667  0.83333333]]
--------------------
The null vectors are
--------------------
[-0.5         0.83333333 -0.16666667 -0.16666667]
[-0.5        -0.16666667  0.83333333 -0.16666667]
[-0.5        -0.16666667 -0.16666667  0.83333333]


The null vectors are different because null vectors are not uniquily determined, and in the earlier chapter they were determined by inspection but here they are generated by an algorithm. Different approches result in different choices of null vectors. They do however span the same space. This can be seen with the transformations. 

$\mathbf{w_i} = - \mathbf{v_i} - \frac{1}{3}\Sigma_j \mathbf{v_j}$ 

$\mathbf{v_i} = - \mathbf{w_i} + \frac{1}{6}\Sigma_j \mathbf{w_j}$

where $\mathbf{w_i}$ are the null vectors from the earlier chapter, $\mathbf{v_i}$ are the SVD null vectors and i and j range from 1 to 3

In [2]:
w1 = -((4/3)*Vh[1,:] + (1/3)*Vh[2,:] + (1/3)*Vh[3,:])
w2 = -((1/3)*Vh[1,:] + (4/3)*Vh[2,:] + (1/3)*Vh[3,:])
w3 = -((1/3)*Vh[1,:] + (1/3)*Vh[2,:] + (4/3)*Vh[3,:])
w1[np.abs(w1) < 1e-15] = 0
w2[np.abs(w2) < 1e-15] = 0
w3[np.abs(w3) < 1e-15] = 0
print(w1)
print(w2)
print(w3)
print("-"*20)
print(-(5/6)*w1 + (1/6)*w2 + (1/6)*w3)
print(-(1/6)*w1 + (5/6)*w2 + (1/6)*w3)
print(-(1/6)*w1 + (1/6)*w2 + (5/6)*w3)

[ 1. -1.  0.  0.]
[ 1.  0. -1.  0.]
[ 1.  0.  0. -1.]
--------------------
[-0.5         0.83333333 -0.16666667 -0.16666667]
[ 0.83333333  0.16666667 -0.83333333 -0.16666667]
[ 0.83333333  0.16666667 -0.16666667 -0.83333333]
